import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Football Live Now",
  description: "Generated by jenkx dev",
  icons: {
    icon: [
      { url: '/globe.svg', type: 'image/svg+xml' },
      { url: '/favicon-16x16.png', type: 'image/png', sizes: '16x16' },
      { url: '/favicon-32x32.png', type: 'image/png', sizes: '32x32' },
    ],
    apple: ['/apple-touch-icon.png'
    ]
  },
  keywords: ['football', 'live scores', 'fixtures', 'soccer', 'live updates', 'football leagues', 'match results', 'sports app', 'premier league', 'champions league', 'la liga', 'serie a', 'bundesliga', 'football news'],
  authors: [{ name: 'Jenkins Dev', url: 'https://jenkinsuwagbaib.netlify.app' }],
  creator: 'Jenkins Dev',
  openGraph: {
    title: 'Football Live Now',
    description: 'Live football scores and fixtures for major leagues worldwide.',
    url: 'https://livenow1.netlify.app',
    siteName: 'Live Now',
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Football Live Now',
    description: 'Live football scores and fixtures for major leagues worldwide',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
